# Generated by Django 4.0.3 on 2022-04-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsyshome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='libsys/img'),
        ),
    ]
