# Generated by Django 4.0.3 on 2022-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsyshome', '0002_alter_books_desc_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='libsys/pdf'),
        ),
    ]
