# Generated by Django 4.0.3 on 2022-04-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsyshome', '0004_alter_books_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='libsys/pdf'),
        ),
    ]
